name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: CI
        uses: actions/checkout@v3
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Running lint
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        run: yarn lint
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: [install, lint]

    steps:
      - name: Build
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: yarn build
      - name: Release
        uses: cycjimmy/semantic-release-action@v2.7.0
        id: semantic
        with:
          branch: main
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
